# *******************************************************************
## Highbay setup parameters.
# Names of each machine type.
machine_type_names:
  - "Loading"
  - "Mega Stitch"
  - "RF Weld"
  - "Perimeter"
  - "Inspection"

# Abbreviations to use when drawing schedules.
machine_type_abvs:
  - "L"
  - "MS"
  - "RF"
  - "P"
  - "I"

# Number of each machine type.
machine_type_nums:
  - 1
  - 1
  - 1
  - 1
  - 1

# Pose for each machine. [x, y, θ].
machine_locations:
  - [0.0, 0.0, 0.0]
  - [10.0, 10.0, 0.0]
  - [10.0, 0.0, 0.0]
  - [0.0, 20.0, 10.0]
  - [15.0, 15.0, 0.0]

# Pose for each needle. [x, y, θ].
needle_locations:
  - [0.0, 0.0, 0.0]
  - [10.0, 10.0, 0.0]
  - [10.0, 0.0, 0.0]
  - [0.0, 20.0, 10.0]
  - [15.0, 15.0, 0.0]


# # *******************************************************************
# ## Anchor setup parameters.
# # Names of each machine type.
# machine_type_names:
#   - "Loading"
#   - "Mega"
#   - "Vinyl"
#   - "Hem"
#   - "Tack"
#   - "Weld"
#   - "Grommet"
#   - "Inspection"

# # Abbreviations to use when drawing schedules.
# machine_type_abvs:
#   - "L"
#   - "MS"
#   - "V"
#   - "H"
#   - "T"
#   - "RF"
#   - "G"
#   - "I"

# # Number of each machine type.
# machine_type_nums:
#   - 1
#   - 1
#   - 1
#   - 1
#   - 1
#   - 1
#   - 1
#   - 1
# # machine_type_nums:
# #   - 2
# #   - 2
# #   - 2
# #   - 4
# #   - 2
# #   - 4
# #   - 4
# #   - 1

# # Pose for each machine. [x, y, θ].
# machine_locations:
#   - [0.0, 0.0, 0.0]
#   - [10.0, 10.0, 0.0]
#   - [10.0, 0.0, 0.0]
#   - [0.0, 20.0, 10.0]
#   - [15.0, 15.0, 0.0]
#   - [0.0, 0.0, 0.0]
#   - [0.0, 0.0, 0.0]
#   - [0.0, 0.0, 0.0]

# # Pose for each needle. [x, y, θ].
# needle_locations:
#   - [0.0, 0.0, 0.0]
#   - [10.0, 10.0, 0.0]
#   - [10.0, 0.0, 0.0]
#   - [0.0, 20.0, 10.0]
#   - [15.0, 15.0, 0.0]
#   - [0.0, 0.0, 0.0]
#   - [0.0, 0.0, 0.0]
#   - [0.0, 0.0, 0.0]