#!/usr/bin/env python3
'''
Rensselaer Polytechnic Institute - Julius Lab
ARM Project
Author - Chukwuemeka Osaretin Ike

Description:
    Constructs and shows the Supervisor GUI.
'''
import sys

from PyQt5.QtWidgets import QApplication
from supervisor_gui.supervisor_gui import SupervisorGUI


if __name__ == '__main__':
    app = QApplication(sys.argv)
    gui = SupervisorGUI()
    sys.exit(app.exec())