---
uint32 fleet_size
string[] robot_names
string[] robot_command_topics           # used by OG to command the physical robots.
string[] robot_frame_command_topics     # used by OG to command the virtual robot frames.
string[] real_robot_frame_names
string[] virtual_robot_frame_names
string[] robot_desired_state_topics     # used by swarm_control.py to send robot desired poses.
string tf_changer_topic                 # used by OG to update specific TF frames.
string robot_enable_status_topic        # used by OG to enable and disable robots while on tasks.