uint32 ticket_id                    # ticket whose assignments we want.
---
uint32 num_assigned_robots          # number of robots assigned to the ticket.
uint32[] assigned_robot_ids         # IDs of the robots assigned to the ticket.