# No request data.
---
Ticket[] all_tickets    # set of all tickets.
uint32[] waiting        # IDs of waiting tickets.
uint32[] ready          # IDs of ready tickets.
uint32[] ongoing        # IDs of ongoing tickets.
uint32[] done           # IDs of done tickets.