#!/usr/bin/env python3
'''
Rensselaer Polytechnic Institute - Julius Lab
ARM Project
Author - Chukwuemeka Osaretin Ike

Description:
'''
from task_scheduler.task_scheduler import TaskScheduler

if __name__ == "__main__":
    scheduler = TaskScheduler()