gazebo_ros_control:
  pid_gains:
    front_left_wheel: {p: 0.5, i: 0.01, d: 0}
    front_right_wheel: {p: 0.5, i: 0.01, d: 0}
    rear_left_wheel: {p: 0.5, i: 0.01, d: 0}
    rear_right_wheel: {p: 0.5, i: 0.01, d: 0}
