# Number of robots available.
num_robots: 4

# Frame topics for each robot. Controlling these controls the TF frame
# and not the physical robot.
robot_frame_command_topic: "just_robot_vel_"

# Command topics for each robot. Controlling these controls the phyiscal robot.
robot_command_topic: "/d/cmd_vel"

# Virtual (desired) robot (control point) frame names.
virtual_robot_frame: "tf_robot_"

# Actual robot (control point) frame names.
# Needed to be able to use the syncing desired robot frames function
real_robot_frame: "d_tf_base_link"

# Name of each robot. Used in the GUI.
robot_name: "D_"

# Robot node names.
robot_node_names:
  - ["/uwb_front_oarbot_silver","/uwb_back_oarbot_silver","/sensor_fusion_oarbot_silver","/oarbot_silver_ctrl"]
  - ["/uwb_front_oarbot_blue","/uwb_back_oarbot_blue","/sensor_fusion_oarbot_blue","/oarbot_blue_ctrl"]
  - []
  - []
  - []
  - []