#!/usr/bin/env python3
'''
Rensselaer Polytechnic Institute - Julius Lab
ARM Project
Author - Chukwuemeka Osaretin Ike

Description:
'''
from robot_assigner.robot_assigner import RobotAssigner


if __name__ == "__main__":
    assigner = RobotAssigner()