#!/usr/bin/env python3
'''
Rensselaer Polytechnic Institute - Julius Lab
ARM Project
Author - Chukwuemeka Osaretin Ike

Description:
'''
from ticket_manager.ticket_manager import TicketManager


if __name__ == "__main__":
    manager = TicketManager()